version: '3.8'
services:

#PHP and Apache Services
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html
      - ./msmtprc:/etc/msmtprc
    networks:
      - internal_network

#Mail server Service
  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    ports:
      - "1080:80"
      - "1025:25"
    networks:
      - internal_network

#Database Service
  database:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal_network

#Database administration Service
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    networks:
      - internal_network

#Docker Networks
networks:
  internal_network:
    driver: bridge
